---
abstract: 'Documentation and tools for using Platypus with the Rust programming language'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  FFI::CheckLib: '0'
  File::Which: '0'
  File::chdir: '0'
  IPC::Run3: '0'
  Module::Build: '0.38'
  Module::Build::FFI: '0.49'
  Test::Script: '1.09'
configure_requires:
  File::Which: '0'
  File::chdir: '0'
  Module::Build: '0.38'
  Module::Build::FFI: '0.49'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-Platypus-Lang-Rust
no_index:
  directory:
    - examples
provides:
  FFI::Platypus::Lang::Rust:
    file: lib/FFI/Platypus/Lang/Rust.pm
    version: '0.06'
  Module::Build::FFI::Rust:
    file: lib/Module/Build/FFI/Rust.pm
    version: '0.06'
requires:
  FFI::Platypus: '0.88'
  File::Which: '0'
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#native
  bugtracker: http://github.com/plicease/FFI-Platypus-Lang-Rust/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/plicease/FFI-Platypus-Lang-Rust
version: '0.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
